development:
  adapter: postgresql
  database: ds_development
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: ds_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ds_production
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
